### ISSUE TITLE
Create "like" operator

### ISSUE THREAD

**Issue by furti** [furti/FreeCAD-Reporting#23]
https://www.w3schools.com/sql/sql_like.asp

https://forum.freecadweb.org/viewtopic.php?f=9&t=33403&start=30#p320207

**Comment by luzpaz** [comment]
@furti ping. Are you still developing this ?

**Comment by furti** [comment]
@luzpaz I will come back to this projects and the other FreeCAD projects of mine. But currently I don't know exactly when. I'm busy with a lot of other stuff right now. I hope I manage to get back to my projects in during the year.

**Comment by christoph-mz** [comment]
Hi furti,

are you developing again? I miss the 'like' operator very much. So I hope you will find time to do this. :-)

**Comment by ronnystandtke** [comment]
I would also need this feature. I have a model of a house with many glass doors and wooden doors. The material information is only in the labels, e.g. "Wooden door 1",  "Wooden door 2", "Glass door 5", Glass door 7", ...
To be able to filter against the material I would need the LIKE operator, e.g.
`... WHERE Label LIKE 'Wooden%'`

**Comment by furti** [comment]
@christoph-mz @ronnystandtke  The like operator exists now. It uses % for multiple characters and ? for a single character. I chose ? on purpose, because I think it is less likely to conflict with characters used in document labels than the official wildcard _. At least I have a lot of documents that contain _ in object labels.

I also added function support in the where clause, and the Lower() and Upper() functions. They might be useful when comparing strings. When for example sometimes the `Door` in `Wooden door` has a lowercase d, and sometimes it has a uppercase D. Now you can do something like ```... Where Lower(Label) Like 'Wooden%'```

Edit:
Would be great if you could give me some feedback if you have some time to test the new version. Thanks a lot in advance 😄
